### ISSUE TITLE
Wish/Suggestion: option to open in new tab

### ISSUE THREAD

**Issue by Cade66** [fluks/redirect-link#24]
Hi,

Recent versions of _Redirect Link_ decided to open links in the same tab rather than in the same as previously.
There are pros and cons of course. The decision obviously considered that the pros of opening links in the same tab outnumbered those of opening them in a new tab.

Personally I'd appreciate this be offered as an option. Of course the user can open links in a new tab with the middle-click but for those of us who have set their browser in accordance with the _Open links to another site in a new tab_ policy (a very option of Firefox's _Tab Mix - Links_ extension) the natural habit is to left-click expecting a new tab when applicable accordingly.
Latest example : viewing a video on YouTube, opening _Redirect Link_ and getting the searched info in the same tab, stopping the video of course, obliging the user to page-back and restart the video. Absurd. I could/should have middle-clicked of course but if Redirect Link offered this as an option (why not? Easy I guess) my opinion is that it would be beneficial for all.

Anyway, _Redirect Link_ most appreciated, really handy.

**Comment by fluks** [comment]
> Hi,
> 
> Recent versions of _Redirect Link_ decided to open links in the same tab rather than in the same as previously.
> There are pros and cons of course. The decision obviously considered that the pros of opening links in the same tab outnumbered those of opening them in a new tab.

The reason of the change was because Firefox opens links in the same tab with left mouse button and to new tab with middle button and users asked to honor this behavior in #19.

> Personally I'd appreciate this be offered as an option. Of course the user can open links in a new tab with the middle-click but for those of us who have set their browser in accordance with the _Open links to another site in a new tab_ policy (a very option of Firefox's _Tab Mix - Links_ extension) the natural habit is to left-click expecting a new tab when applicable accordingly.
> Latest example : viewing a video on YouTube, opening _Redirect Link_ and getting the searched info in the same tab, stopping the video of course, obliging the user to page-back and restart the video. Absurd. I could/should have middle-clicked of course but if Redirect Link offered this as an option (why not? Easy I guess) my opinion is that it would be beneficial for all.

You are first to ask, that's one reason it isn't available for an option. But I'm hesitant to add this as an option, because the functionality to open to new tabs is there and the subgroup of Redirect Link users who also use Tab Mix - Links is so small. If this was an option in Firefox, it would be another issue.

I also almost always open links to new tabs when I use Redirect Link. I didn't add this feature to pleasure me, I had to learn to use the middle click.

> Anyway, _Redirect Link_ most appreciated, really handy.

Thank you.

**Comment by Cade66** [comment]
Well, doesn't cost to ask. Thanks anyway.

**Comment by Cade66** [comment]
Hi,

I'm back to this thread I opened last year. I really think that adding the option to open links in a newt tab remains pertinent. I understood/stand the reason why opening by default in a new tab is not implemented (logic), but proposing it as an option would be IMO most welcomed.

Many extensions offer the way links are opened as an option. We get used to them and forget when it comes to _Redirect Link_ that default/forced behavior is to open in the same tab. How many times have I not been annoyed by that, but forget me and consider if you wish the smartness of such an option.

Consider as well for instance the excellent _Swift Selection Search (SSS)_ extension, which offers even more options:

![1](https://user-images.githubusercontent.com/65161029/215359954-d8aa54f2-53c9-41bb-89d3-62605ad04b11.png)

I truly hope you take these arguments into consideration if you ever plan to update current _Redirect Link_.

Thanks :=)

**Comment by fluks** [comment]
Sorry, for taking this long but perhaps I can implement this, that there is an option to always open to a new tab. That's what you want, right? It's not a lot of work. I just feel that the feature already is there and I'm doing double the work. But it's not for nothing if you really think it's important for you. And it doesn't affect other users who don't need this feature. So, I will do this and test it and probably publish it because I don't see any problems with it other than work.

**Comment by Cade66** [comment]
Hi @fluks and thanks for considering my suggestion. An option to 'always open in a new tab' is indeed a wish, not in terms of what I'd consider as logically required given indeed 'Redirect Link' is totally coherent but rather as an extra comfort for those as myself who 1- prefer a new tab for opening a redirected url, 2- happen to forger the middle-click logical mean to do so because they are used to other extensions which provide that option. As you see this is all related to comfort, not to anything I'd consider as imperative :=)

Whatever, enjoying as many others this slick 'Redirect Link' ... with or without an extra option!

**Comment by fluks** [comment]
I sent an update. Should be available for download shortly.

**Comment by Cade66** [comment]
Just updated _Redirect Link_ to version _**4.2.0**_, checked _Open New Tab_, works perfectly. Many thanks, most appreciated :=)
